### PR TITLE
Add generator for config manpages

### PR DESCRIPTION
**Pull request by chrisduerr**
This patch adds the `update_config.sh` script which completely
autonomously updates the config documentation from a manpage directory
passed to it. No manual intervention is necessary.

### CODE REVIEW

**Comment by kchibisov** [comment]
Maybe we should somehow list the version you're looking into, I'd also expect to have links to configs for previous versions.

Also, maybe we should use monospace font for the man pages?

**Comment by chrisduerr** [comment]
> Maybe we should somehow list the version you're looking into, I'd also expect to have links to configs for previous versions (not as of now).

Yeah that's something I want to add, but I wanted to make sure we had anything at all first.

I think a good solution would be to have a directory with all the configs and then just add a little drop down where you can select which version you want, with a symlink to some "latest" version thingy.

> Also, maybe we should use monospace font for the man pages?

That's not the worst idea, though I do think that the current font look just fine and might be more "natural" to read for people? Since we don't rely on heavy codeblocks I don't think it is an issue.

**Comment by kchibisov** [comment]
I'd still like to keep it around until the actual release and merge right before it.

**Comment by chrisduerr** [comment]
> I'd still like to keep it around until the actual release and merge right before it.

Yeah that was my plan.

**Comment by kchibisov** [comment]
```diff
diff --git a/manpage_template.html b/manpage_template.html
index 6753f35..72903df 100644
--- a/manpage_template.html
+++ b/manpage_template.html
@@ -6,6 +6,7 @@
     <title>Alacritty</title>
     <link rel="stylesheet" href="base.css" type="text/css" media="all">
     <link rel="stylesheet" href="changelog.css" type="text/css" media="all">
+    <link rel="stylesheet" href="man.css" type="text/css" media="all">
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.4.0/css/font-awesome.min.css">
     <link rel="icon" href="alacritty-simple.svg">
   </head>
diff --git a/static/base.css b/static/base.css
index 3623a38..80ba002 100644
--- a/static/base.css
+++ b/static/base.css
@@ -2,7 +2,6 @@ body {
   background-color: #181818;
   color: #aaaaaa;
   margin: unset;
-  font-size: 1.2em;
   font-family: sans-serif;
 }
 
@@ -71,3 +70,7 @@ h1 {
   padding-top: 20px;
   margin: 20px 0;
 }
+
+li {
+  list-style: square;
+}
diff --git a/static/changelog_0_12_2.html b/static/changelog_0_12_2.html
index 9cb3f11..ebaab6c 100644
--- a/static/changelog_0_12_2.html
+++ b/static/changelog_0_12_2.html
@@ -17,6 +17,7 @@
           lacritty
         </a>
         <nav>
+          <a href="config-alacritty.html">Configuration</a>
           <a href="changelog.html">Changelog</a>
           <a href="https://github.com/alacritty/alacritty" target="_blank"><i class="fa fa-github"></i></a>
         </nav>
diff --git a/static/changelog_0_12_3.html b/static/changelog_0_12_3.html
index 3664c8e..4d31ce0 100644
--- a/static/changelog_0_12_3.html
+++ b/static/changelog_0_12_3.html
@@ -17,6 +17,7 @@
           lacritty
         </a>
         <nav>
+          <a href="config-alacritty.html">Configuration</a>
           <a href="changelog.html">Changelog</a>
           <a href="https://github.com/alacritty/alacritty" target="_blank"><i class="fa fa-github"></i></a>
         </nav>
diff --git a/static/index.css b/static/index.css
index 921eb07..273fc38 100644
--- a/static/index.css
+++ b/static/index.css
@@ -5,10 +5,6 @@
   background: #262626;
 }
 
-#feature-list {
-  list-style: square;
-}
-
 #feature-list div {
   display: inline-block;
 }
diff --git a/static/man.css b/static/man.css
new file mode 100644
index 0000000..7ef5c56
--- /dev/null
+++ b/static/man.css
@@ -0,0 +1,13 @@
+p,table,h1 {
+  font-family: monospace;
+}
+
+em {
+  font-style: normal;
+  color: #90a959;
+}
+
+strong,h1 {
+  font-weight: normal;
+  color: #6a9fb5;
+}
```

**Comment by kchibisov** [comment]
@chrisduerr that's a small diff I used to play with how it renders.  An example 

picture

**Review by kchibisov — APPROVED** [review]

**Comment by kchibisov** [comment]
Will need one more regeneration of man pages.

**Review by kchibisov — APPROVED** [review]

**Pull request merged**
