### PR TITLE
Properly aligning the alacritty logo on the top

### PR DESCRIPTION
**Pull request by tusqasi**
logo and the text weren't on the same line.
#1 has more info

### CODE REVIEW

**Review by chrisduerr — CHANGES_REQUESTED** [review]
This doesn't actually work out well at all when it comes to my font:

tmp

I assume that's the case for most fonts and I don't think there's any good solution to alignment of images to arbitrary fonts. Something I've considered during creation already though is to just transform everything into a single image, I think that's realistically the only way this could every look properly on all systems.

**Comment by tusqasi** [comment]
Can't we just make the font constant. Is that possible?
Will finding a proper font and then using it work?

Single image solution is workable too I guess.

**Comment by chrisduerr** [comment]
> Can't we just make the font constant. Is that possible?
Will finding a proper font and then using it work?

No.

**Comment by chrisduerr** [comment]
Closing because dead.

**Pull request closed without merging**
